### ISSUE TITLE
Needs an option for no fall damage like deathrun redux.

### ISSUE THREAD

**Issue by gdfsgdfg** [Mikusch/deathrun#21]
Ditto.

**Comment by worMatty** [comment]
Which maps is this needed for?

**Comment by gdfsgdfg** [comment]
Simulation is a recent popular one that compensates by having health packs scattered around practically forcing low health classes to go for them unlike neonoir that just disables fall damage with the map itself.

Obviously fall damage is not enough kill you in most dr maps, but its a nice option.

**Comment by gdfsgdfg** [comment]
Also I have a question what to set dr_speed_modifier to, I set it to 300.0 which is supposed to be pyro's speed. But that's not the case since it makes everyone go at super speeds. I've set it at 100.0 which seems almost right.

**Comment by Mikusch** [comment]
I don't know whether I really want to add this, but it's something I'll keep in mind. Usually it's on the map to enable or disable fall damage where necessary. I'd argue that a map containing health kits was built with fall damage in mind, thus it should not be disabled.

> Also I have a question what to set dr_speed_modifier to, I set it to 300.0 which is supposed to be pyro's speed. But that's not the case since it makes everyone go at super speeds. I've set it at 100.0 which seems almost right.

It's a modifier, not an absolute value. Setting `dr_speed_modifier` to `300` will add 300 speed to all classes. Setting it to `-50` will remove speed from all classes, etc. I always deal with modifiers rather than absolute values in my plugins because there is a chance Valve might change speed values of classes.

If you want to set every class' speed to 300, you'll have to use the `dr_speed_modifier_scout`, `dr_speed_modifier_soldier`, etc. convars.

**Comment by worMatty** [comment]
I understand your frustration about fall damage but I cam concerned that adding the ability to disable it to a deathrun plugin will cause server operators to disable it for all maps. This is bad because it prevents maps from using fall damage as part of their design and it can cause mappers to believe that fall damage will always be disabled and that they should not deal with it in their map. Deathrun plugins have a history of disabling things because of flawed maps and it limits what mappers can do as a result. 

I suggest you contact the map author and leave feedback on their design choice. If the fall damage is unavoidable, I believe that's not fair and that the fall damage should be prevented in that case rather than need healing (maybe it's due to the mapper's lack of knowledge?). However if the fall damage is avoidable (for example by taking a longer route), that is arguably a design decision that shouldn't be interfered with.

**Comment by gdfsgdfg** [comment]
Redux always reverted all changes it did if it detected a non-dr map. Anyway you're kinda making no sense there, miku's bhop plugin has a toggle to disable fall damage as well. My server config has a unload for the deathrun plugin and "maps with prefixes" plugin on dr to enable it from the disabled folder and works just fine when swapping to other maps and game modes.

Anyway for those that are lazy like me and want 300 hu/s on all classes like older dr use these settings.

dr_speed_modifier_scout -100.0
dr_speed_modifier_soldier 60.0
dr_speed_modifier_demoman 20.0
dr_speed_modifier_medic -20.0
dr_speed_modifier_heavy 70.0
dr_speed_modifier_spy -20.0

**Comment by worMatty** [comment]
My apologies if I misled you but I was talking about all *deathrun* maps. I did not think it would be necessary to specify that. I will edit my post.

**Comment by gdfsgdfg** [comment]
// Pyro - Melee [Slot 3]
	"214"	// The Powerjack
	{
		"attributes"
		{
			"1"
			{
				"name"	"move speed bonus"
				"value"	"1.0"
			}
		}
	}

Also added this so no speed boost from power jack.

**Comment by gdfsgdfg** [comment]
I also noticed that you can't spectate death either, would like that to be an option as well.

**Comment by Mikusch** [comment]
`mp_forcecamera` exists

**Comment by gdfsgdfg** [comment]
Neat, I'll use that.

**Comment by gdfsgdfg** [comment]
Neat, I'll use that.

I'll close this for now since I found a fall damage related plugin, hopefully doesn't make more side effects..
